import selectedElement from "./element.js";

/*const newElement = ["Hydrogen", "Helium", "Lithium", "Beryllium", "Boron", 
"Carbon", "Nitrogen", "Oxygen", "Fluorine", "Neon", 
"Sodium", "Magnesium", "Aluminum", "Silicon", "Phosphorus", 
"Sulfur", "Chlorine", "Argon", "Potassium", "Calcium", 
"Scandium", "Titanium", "Vanadium", "Chromium", "Manganese"] */

//funFacts generated by ChatGPT
const funFact = {
    "Hydrogen": "Hydrogen is the lightest and most abundant element in the universe. It makes up about 75% of the universe's elemental mass.",
    "Helium": "Helium is the only element discovered in space before it was found on Earth. It was first detected in the Sun's spectrum in 1868.",
    "Lithium": "Lithium is used in the treatment of bipolar disorder and depression. It's also a key component of lithium-ion batteries, which power many electronic devices.",
    "Beryllium": "Beryllium is lighter than aluminum but stronger than steel. It's used in aerospace components and nuclear reactors due to its strength and ability to withstand high temperatures.",
    "Boron": "Boron is found in many cleaning products, such as detergents and bleaches, because of its ability to remove stains.",
    "Carbon": "Carbon is essential for life and is found in all known living organisms. It has the ability to form long chains and complex structures, making it the basis for organic chemistry.",
    "Nitrogen": "Nitrogen gas makes up about 78% of Earth's atmosphere. It's essential for life, as it's a key component of proteins and nucleic acids.",
    "Oxygen": "Oxygen is the most abundant element in Earth's crust, oceans, and atmosphere. It's essential for respiration in most living organisms.",
    "Fluorine": "Fluorine is the most reactive and electronegative of all the elements. It's used in toothpaste and water fluoridation to prevent dental cavities.",
    "Neon": "Neon lights get their name from the Greek word 'neos,' meaning 'new.' Neon lights were first demonstrated in 1910 by French inventor Georges Claude.",
    "Sodium": "Sodium is a highly reactive metal that explodes when it comes into contact with water. It's a key component of table salt (sodium chloride).",
    "Magnesium": "Magnesium is essential for plant and animal life. It's involved in over 300 biochemical reactions in the human body and is found in foods like nuts, seeds, and leafy green vegetables.",
    "Aluminum": "Aluminum is the most abundant metal in Earth's crust. It's lightweight, non-toxic, and corrosion-resistant, making it ideal for a wide range of applications, including packaging, transportation, and construction.",
    "Silicon": "Silicon is the second most abundant element in Earth's crust, after oxygen. It's a key component of semiconductors, which are used in electronic devices like computers and smartphones.",
    "Phosphorus": "Phosphorus is essential for all living organisms. It's a key component of DNA, RNA, and ATP, which are essential for energy transfer in cells.",
    "Sulfur": "Sulfur is found in many minerals, such as gypsum and Epsom salt, as well as in proteins and vitamins. It's also used in the production of sulfuric acid, which is one of the most widely used industrial chemicals.",
    "Chlorine": "Chlorine is used to disinfect drinking water and swimming pools due to its ability to kill bacteria and other microorganisms. It's also used in the production of plastics, solvents, and pesticides.",
    "Argon": "Argon is the third most abundant gas in Earth's atmosphere, after nitrogen and oxygen. It's used in welding, lighting, and as a protective atmosphere in the production of titanium and other reactive elements.",
    "Potassium": "Potassium is essential for the functioning of cells, nerves, and muscles in the human body. It's found in many fruits and vegetables, such as bananas, potatoes, and spinach.",
    "Calcium": "Calcium is the most abundant mineral in the human body. It's essential for bone and teeth health, muscle function, nerve transmission, and blood clotting.",
    "Scandium": "Scandium is used in the production of high-strength aluminum alloys used in aerospace and defense applications. It's also used in the manufacturing of high-intensity lamps and lasers.",
    "Titanium": "Titanium is known for its strength, durability, and corrosion resistance. It's used in aerospace components, medical implants, and sporting equipment.",
    "Vanadium": "Vanadium is used as an alloying agent in steel production, resulting in stronger, more durable steel. It's also used in the production of batteries, ceramics, and pigments.",
    "Chromium": "Chromium is used in stainless steel production, which is resistant to corrosion and staining. It's also used in chrome plating, paints, and dyes.",
    "Manganese": "Manganese is essential for the production of steel. It improves the strength, hardness, and workability of steel when used as an alloying agent. Manganese compounds are also used in batteries, fertilizers, and pigments."
  };

//this tests to make sure when a key is called, it returns the proper value from the array.  
//console.log(funFact.Nitrogen)
const getFunFact = () => {
  const element = selectedElement  
  return funFact[element] 
};
console.log(getFunFact())
  
//export default funFact;